name: Git Version
on: [push]

jobs:
  branch_version:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          output-file: 'MY_CUSTOM_CHANGELOG.md'
          skip-commit: 'false'
        
      - name: see
        run: echo "${{ steps.nextversion.outputs.nextVersion }}"