# .github/workflows/version.yml
name: Git Version
on: [push]

jobs:
  branch_version:
    runs-on: ubuntu-latest
    steps:
    - name: Normalize branch name
      id: normalizeversion
      uses: Slidem/branch-name-normalizer@v1.0.0
    - name: show normalize
      run: echo ${{ steps.normalizeversion.outputs.normalized }}

    - name: Generate Version
      id: versioning
      uses: sceccotti89/Github-Action-Versioning@v1.0.5
    - name: Get the output version
      run: echo "Version = ${{ steps.versioning.outputs.version }}"

  gitversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        uses: codacy/git-version@2.2.0
        id: gitversion
        with:
          prefix: v
      - name: debug
        run: echo ${{ steps.get-version.outputs.version }}